### ISSUE TITLE
delay!(x,0.9) deletes the last half of x

### ISSUE THREAD

**Issue by Darf-Ferrara** [org-arl/SignalAnalysis.jl#48]
```
julia> x = signal([1.,2,3,4,5,6,7],3)
julia> delay!(x,.99999999999)
SampledSignal @ 3.0 Hz, 7-element Vector{Float64}:
 9.821130612501859e-12
 1.0000000000063198
 2.0000000000155396
 3.000000000002601
 0.0
 0.0
 0.0
```
It seems that any delay! less than 1.0 will erase half the signal.

**Comment by mattcbro** [comment]
I can verify this bug is happening.  In Julia Version 1.11.1 and  SignalAnalysis v0.9.1 on linux Mint 21.3 Cinnamon.  The last half of the signal get's zero'd out.  It makes this important tool unusable sad to say.

**Comment by mchitre** [comment]
Taking a look at it. Seems to happen for some fractional delays.

**Comment by mchitre** [comment]
Fixed in https://github.com/org-arl/SignalAnalysis.jl/commit/8a4ee1626b0e75001b34e0a6b9a34f5a11a788f9. Patch release 0.9.2 should be available shortly.

**Comment by Darf-Ferrara** [comment]
Thanks for the quick update. This is a great package!
